apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - rbac
  - pipelines/kong-plugin-rate-limiting.yaml
  - pipelines/kong-plugin-correlation-id.yaml
  - pipelines/kong-plugin-transformers.yaml
  - pipelines/kong-plugin-cors.yaml
  - pipelines/kong-plugin-request-size-limiting.yaml
  - pipelines/kong-plugin-request-termination.yaml
  - pipelines/kong-plugin-ip-restriction.yaml
  - pipelines/kong-plugin-key-auth.yaml
  - pipelines/kong-plugin-basic-auth.yaml
  - pipelines/kong-plugin-jwt.yaml
  - pipelines/kong-plugin-acl.yaml
  - pipelines/kong-plugin-hmac-auth.yaml
  - pipelines/kong-plugin-prometheus.yaml
  - pipelines/kong-plugin-http-log.yaml
  - pipelines/kong-plugin-opentelemetry.yaml
