apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: kong-plugin-tester
  namespace: kong-demo
  labels:
    app.kubernetes.io/part-of: kong-community-crc-lab
subjects:
  - kind: ServiceAccount
    name: kong-plugin-tester
    namespace: kong-demo
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: kong-plugin-tester
